config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lezzidan/compsssqaaas:
      branch: main
      repo: https://github.com/lezzidan/compsssqaaas.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lezzidan/compsssqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-eggplant-seahorse.sh
        container: qc.acc_whiny-firebrick-seal
  QC.Doc:
    repos:
      github.com/lezzidan/compsssqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-eggplant-fossa.sh
        container: qc.doc_fuzzy-pumpkin-urchin
      github.com/lezzidan/compsssqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-harlequin-peccary.sh
        container: qc.doc_slaphappy-cyan-insect
      github.com/lezzidan/compsssqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cyan-frog.sh
        container: qc.doc_whiny-saffron-neanderthal
      github.com/lezzidan/compsssqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-lemon-hummingbird.sh
        container: qc.doc_zippy-razzmatazz-goat
  QC.Lic:
    repos:
      github.com/lezzidan/compsssqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-heliotrope-hyena.sh
        container: qc.lic_crabby-amethyst-bulldog
  QC.Sec:
    repos:
      github.com/lezzidan/compsssqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-tangerine-hummingbird.sh
        container: qc.sec_thirsty-beige-foxhound
  QC.Sty:
    repos:
      github.com/lezzidan/compsssqaaas checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-orchid-dingo.sh
        container: qc.sty_sloppy-lavender-gopher
      github.com/lezzidan/compsssqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-eggplant-wolf.sh
        container: qc.sty_bumpy-cornflower-bandicoot
      github.com/lezzidan/compsssqaaas hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-aquamarine-newfoundland.sh
        container: qc.sty_shaggy-amethyst-frog
      github.com/lezzidan/compsssqaaas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-maroon-boar.sh
        container: qc.sty_queasy-myrtle-frigatebird
      github.com/lezzidan/compsssqaaas rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-wisteria-mist.sh
        container: qc.sty_beady-olive-kingfisher
  QC.Ver:
    repos:
      github.com/lezzidan/compsssqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-emerald-skunk.sh
        container: qc.ver_stinky-indigo-serval
timeout: 5400
