config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lezzidan/compsssqaaas:
      branch: main
      repo: https://github.com/lezzidan/compsssqaaas.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lezzidan/compsssqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-lavender-tuatara.sh
        container: qc.acc_stinky-cobalt-alligator
  QC.Doc:
    repos:
      github.com/lezzidan/compsssqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cobalt-salamander.sh
        container: qc.doc_muggy-taupe-rhinoceros
      github.com/lezzidan/compsssqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-myrtle-deer.sh
        container: qc.doc_bluesy-platinum-foxhound
      github.com/lezzidan/compsssqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sapphire-cow.sh
        container: qc.doc_bumpy-chestnut-whale
      github.com/lezzidan/compsssqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-thistle-ragdoll.sh
        container: qc.doc_sunny-aquamarine-ferret
  QC.Lic:
    repos:
      github.com/lezzidan/compsssqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-coral-fly.sh
        container: qc.lic_geeky-sepia-chin
  QC.Met:
    repos:
      github.com/lezzidan/compsssqaaas cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ready-asparagus-turkey.sh
        container: qc.met_surly-lime-discus
  QC.Sec:
    repos:
      github.com/lezzidan/compsssqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-corn-owl.sh
        container: qc.sec_ugly-zucchini-sponge
  QC.Sty:
    repos:
      github.com/lezzidan/compsssqaaas checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-tomato-argentino.sh
        container: qc.sty_shaggy-pear-russel
      github.com/lezzidan/compsssqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-amber-lemming.sh
        container: qc.sty_droopy-lavender-scorpion
      github.com/lezzidan/compsssqaaas hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-amaranth-woodlouse.sh
        container: qc.sty_silly-white-chipmunk
      github.com/lezzidan/compsssqaaas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-celadon-budgerigar.sh
        container: qc.sty_cozy-ultramarine-dragonfly
      github.com/lezzidan/compsssqaaas rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-myrtle-wallaby.sh
        container: qc.sty_shaky-wheat-coral
  QC.Ver:
    repos:
      github.com/lezzidan/compsssqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-persimmon-macaw.sh
        container: qc.ver_lovely-magnolia-woodlouse
timeout: 5400
