config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lezzidan/compsssqaaas:
      branch: main
      repo: https://github.com/lezzidan/compsssqaaas.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lezzidan/compsssqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-copper-fly.sh
        container: qc.acc_stealthy-coral-stingray
  QC.Doc:
    repos:
      github.com/lezzidan/compsssqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-dandelion-pinscher.sh
        container: qc.doc_shabby-cerise-fish
      github.com/lezzidan/compsssqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ruby-snail.sh
        container: qc.doc_sleepy-cyan-barnacle
      github.com/lezzidan/compsssqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-mauve-dodo.sh
        container: qc.doc_randy-pear-eagle
      github.com/lezzidan/compsssqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-aqua-stingray.sh
        container: qc.doc_jumpy-apricot-caiman
  QC.Lic:
    repos:
      github.com/lezzidan/compsssqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-orange-badger.sh
        container: qc.lic_squirrely-malachite-clam
  QC.Met:
    repos:
      github.com/lezzidan/compsssqaaas cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-copper-tang.sh
        container: qc.met_skanky-rose-angora
  QC.Sec:
    repos:
      github.com/lezzidan/compsssqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-wheat-gibbon.sh
        container: qc.sec_geeky-cinnabar-koala
  QC.Sty:
    repos:
      github.com/lezzidan/compsssqaaas checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-bronze-lionfish.sh
        container: qc.sty_pasty-indigo-zebra
      github.com/lezzidan/compsssqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-green-hornet.sh
        container: qc.sty_jumpy-sepia-gorilla
      github.com/lezzidan/compsssqaaas hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-buff-molly.sh
        container: qc.sty_whiny-gold-chin
      github.com/lezzidan/compsssqaaas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-silver-seal.sh
        container: qc.sty_stinky-dandelion-devil
      github.com/lezzidan/compsssqaaas rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-maroon-gharial.sh
        container: qc.sty_slaphappy-mustard-fox
  QC.Ver:
    repos:
      github.com/lezzidan/compsssqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-thistle-bandicoot.sh
        container: qc.ver_stinky-xanthic-drever
timeout: 5400
